/*
 * Copyright (c)  2023. ONERA
 * This file is part of Dalculator
 *
 * Dalculator is free software ;
 * you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation ;
 * either version 2 of  the License, or (at your option) any later version.
 *
 * PML Analyzer is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY ;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this program ;
 *  if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

package dalculator.gui;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DalculatorGui.java
 *
 * Created on 9 mars 2011, 11:16:40
 */

/**
 *
 * @author rdelmas
 */
public class DalculatorGui extends javax.swing.JFrame {

    /** Creates new form DalculatorGui */
    public DalculatorGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indepSolverGroup = new javax.swing.ButtonGroup();
        dalSolverGroup = new javax.swing.ButtonGroup();
        dalRuleGroup = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        paramsPanel = new javax.swing.JPanel();
        indepPanel = new javax.swing.JPanel();
        enableIndep = new javax.swing.JCheckBox();
        indepSAT4J = new javax.swing.JRadioButton();
        indepWBO = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nofResourcesStart = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        indepResultsFile = new javax.swing.JTextField();
        selectIndepResultsFile = new javax.swing.JButton();
        selectIndepUdefFile = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        indepUdefFile = new javax.swing.JTextField();
        nofResourcesStop = new javax.swing.JTextField();
        indepSaveAlloc = new javax.swing.JCheckBox();
        dalPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dalSAT4J = new javax.swing.JRadioButton();
        dalWBO = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        dalRule1 = new javax.swing.JRadioButton();
        dalRule2 = new javax.swing.JRadioButton();
        dalRuleMixed = new javax.swing.JRadioButton();
        enableDal = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        selectDalResultsFile = new javax.swing.JButton();
        dalResultsFile = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dalUdefFile = new javax.swing.JTextField();
        selectDalUdefFile = new javax.swing.JButton();
        dalImportIndep = new javax.swing.JCheckBox();
        inputFilesPanel = new javax.swing.JPanel();
        runAnalysis = new javax.swing.JButton();
        seqTableScrollPane = new javax.swing.JScrollPane();
        seqTable = new javax.swing.JTable();
        addSeqFile = new javax.swing.JButton();
        removeSeqFile = new javax.swing.JButton();
        cancelAnalysis = new javax.swing.JButton();
        budgetPanel = new javax.swing.JPanel();
        enableBudget = new javax.swing.JCheckBox();
        selectBudgetResultsFile = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        budgetResultsFile = new javax.swing.JTextField();
        enableMinLatent = new javax.swing.JCheckBox();
        enableMinCheckItv = new javax.swing.JCheckBox();
        enableSumLatent = new javax.swing.JCheckBox();
        enableSumActive = new javax.swing.JCheckBox();
        enableGlobalLambdaMin = new javax.swing.JCheckBox();
        enableMinActive = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        budgetImportIndep = new javax.swing.JCheckBox();
        selectBudgetUdefFile = new javax.swing.JButton();
        budgetUdefFile = new javax.swing.JTextField();
        consolePanel = new javax.swing.JPanel();
        consoleScroller = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        oneraLogoPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DALculator v1.0 - ONERA - 2011");

        topPanel.setBorder(null);

        paramsPanel.setBorder(null);

        indepPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Independence Analysis"));

        enableIndep.setText("enable");
        enableIndep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableIndepActionPerformed(evt);
            }
        });

        indepSolverGroup.add(indepSAT4J);
        indepSAT4J.setSelected(true);
        indepSAT4J.setText("SAT4J");

        indepSolverGroup.add(indepWBO);
        indepWBO.setText("WBO");

        jLabel2.setText("solver :");

        jLabel1.setText("nbRes :");

        nofResourcesStart.setText("4");
        nofResourcesStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nofResourcesStartActionPerformed(evt);
            }
        });

        jLabel8.setText("output :");

        indepResultsFile.setText("indepResults.udef");

        selectIndepResultsFile.setText("select");

        selectIndepUdefFile.setText("select");

        jLabel9.setText("udef :");

        indepUdefFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indepUdefFileActionPerformed(evt);
            }
        });

        nofResourcesStop.setText("10");
        nofResourcesStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nofResourcesStopActionPerformed(evt);
            }
        });

        indepSaveAlloc.setText("save allocation");

        javax.swing.GroupLayout indepPanelLayout = new javax.swing.GroupLayout(indepPanel);
        indepPanel.setLayout(indepPanelLayout);
        indepPanelLayout.setHorizontalGroup(
            indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indepPanelLayout.createSequentialGroup()
                .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indepPanelLayout.createSequentialGroup()
                        .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(indepPanelLayout.createSequentialGroup()
                                .addComponent(indepSAT4J)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(indepWBO))
                            .addGroup(indepPanelLayout.createSequentialGroup()
                                .addComponent(nofResourcesStart, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nofResourcesStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addComponent(enableIndep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indepPanelLayout.createSequentialGroup()
                        .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(indepResultsFile, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(indepUdefFile, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectIndepUdefFile)
                            .addComponent(selectIndepResultsFile)))
                    .addComponent(indepSaveAlloc))
                .addContainerGap())
        );
        indepPanelLayout.setVerticalGroup(
            indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indepPanelLayout.createSequentialGroup()
                .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enableIndep)
                    .addComponent(indepSaveAlloc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nofResourcesStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indepUdefFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectIndepUdefFile)
                    .addComponent(jLabel9)
                    .addComponent(nofResourcesStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(indepSAT4J)
                    .addComponent(indepWBO)
                    .addComponent(jLabel8)
                    .addComponent(indepResultsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectIndepResultsFile))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        dalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("DAL Analysis"));

        jLabel3.setText("solver :");

        dalSolverGroup.add(dalSAT4J);
        dalSAT4J.setSelected(true);
        dalSAT4J.setText("SAT4J");

        dalSolverGroup.add(dalWBO);
        dalWBO.setText("WBO");

        jLabel6.setText("rule :");

        dalRuleGroup.add(dalRule1);
        dalRule1.setSelected(true);
        dalRule1.setText("1");

        dalRuleGroup.add(dalRule2);
        dalRule2.setText("2");

        dalRuleGroup.add(dalRuleMixed);
        dalRuleMixed.setText("1&2");
        dalRuleMixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dalRuleMixedActionPerformed(evt);
            }
        });

        enableDal.setText("enable");

        jLabel4.setText("output :");

        selectDalResultsFile.setText("select");

        dalResultsFile.setText("dalResults.udef");

        jLabel10.setText("udef :");

        selectDalUdefFile.setText("select");

        dalImportIndep.setText("import indep analysis results :");
        dalImportIndep.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout dalPanelLayout = new javax.swing.GroupLayout(dalPanel);
        dalPanel.setLayout(dalPanelLayout);
        dalPanelLayout.setHorizontalGroup(
            dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dalPanelLayout.createSequentialGroup()
                .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dalPanelLayout.createSequentialGroup()
                        .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dalPanelLayout.createSequentialGroup()
                                .addComponent(dalSAT4J)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dalWBO))
                            .addGroup(dalPanelLayout.createSequentialGroup()
                                .addComponent(dalRule1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dalRule2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dalRuleMixed)))
                        .addGap(9, 9, 9)
                        .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)))
                    .addComponent(enableDal))
                .addGap(41, 41, 41)
                .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dalPanelLayout.createSequentialGroup()
                        .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dalResultsFile, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(dalUdefFile, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectDalUdefFile)
                            .addComponent(selectDalResultsFile)))
                    .addComponent(dalImportIndep))
                .addContainerGap())
        );
        dalPanelLayout.setVerticalGroup(
            dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dalPanelLayout.createSequentialGroup()
                .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enableDal)
                    .addComponent(dalImportIndep, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dalUdefFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectDalUdefFile)
                    .addComponent(dalRule1)
                    .addComponent(dalRule2)
                    .addComponent(dalRuleMixed)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDalResultsFile)
                    .addComponent(dalResultsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dalSAT4J)
                    .addComponent(dalWBO)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        inputFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Files"));

        runAnalysis.setText("Analyse");

        seqTable.setModel(new SeqFileTableModel());
        seqTable.getColumnModel().getColumn(1).setCellEditor(new NSevCellEditor());
        seqTable.getColumnModel().getColumn(2).setCellEditor(new XSevCellEditor());
        seqTable.getColumnModel().getColumn(3).setCellEditor(new RefDalCellEditor());
        seqTableScrollPane.setViewportView(seqTable);

        addSeqFile.setText("+");

        removeSeqFile.setText("-");

        cancelAnalysis.setText("Cancel");

        javax.swing.GroupLayout inputFilesPanelLayout = new javax.swing.GroupLayout(inputFilesPanel);
        inputFilesPanel.setLayout(inputFilesPanelLayout);
        inputFilesPanelLayout.setHorizontalGroup(
            inputFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputFilesPanelLayout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(runAnalysis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelAnalysis))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputFilesPanelLayout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(addSeqFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeSeqFile))
            .addComponent(seqTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        inputFilesPanelLayout.setVerticalGroup(
            inputFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputFilesPanelLayout.createSequentialGroup()
                .addComponent(seqTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeSeqFile)
                    .addComponent(addSeqFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAnalysis)
                    .addComponent(runAnalysis)))
        );

        budgetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Budget Analysis"));

        enableBudget.setText("enable");

        selectBudgetResultsFile.setText("select");

        jLabel5.setText("output :");

        budgetResultsFile.setText("budgetResults.txt");
        budgetResultsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetResultsFileActionPerformed(evt);
            }
        });

        enableMinLatent.setText("min of latent lambdas");

        enableMinCheckItv.setText("min of check intervals");

        enableSumLatent.setText("sum of latent lambdas");

        enableSumActive.setText("sum of active lambdas");

        enableGlobalLambdaMin.setText("global lambda min");

        enableMinActive.setText("min of active lambdas");

        jLabel11.setText("udef :");

        budgetImportIndep.setText("import indep analysis results :");
        budgetImportIndep.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        selectBudgetUdefFile.setText("select");

        budgetUdefFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetUdefFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout budgetPanelLayout = new javax.swing.GroupLayout(budgetPanel);
        budgetPanel.setLayout(budgetPanelLayout);
        budgetPanelLayout.setHorizontalGroup(
            budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budgetPanelLayout.createSequentialGroup()
                .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(budgetPanelLayout.createSequentialGroup()
                        .addComponent(enableBudget)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addComponent(budgetImportIndep))
                    .addGroup(budgetPanelLayout.createSequentialGroup()
                        .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(budgetPanelLayout.createSequentialGroup()
                                .addComponent(enableMinLatent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enableMinActive))
                            .addGroup(budgetPanelLayout.createSequentialGroup()
                                .addComponent(enableSumLatent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enableSumActive)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enableMinCheckItv)
                            .addComponent(enableGlobalLambdaMin)))
                    .addGroup(budgetPanelLayout.createSequentialGroup()
                        .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(budgetResultsFile, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                            .addComponent(budgetUdefFile, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(selectBudgetUdefFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectBudgetResultsFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        budgetPanelLayout.setVerticalGroup(
            budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budgetPanelLayout.createSequentialGroup()
                .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enableBudget)
                    .addComponent(budgetImportIndep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enableMinLatent)
                    .addComponent(enableMinActive)
                    .addComponent(enableMinCheckItv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enableSumLatent)
                    .addComponent(enableSumActive)
                    .addComponent(enableGlobalLambdaMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budgetUdefFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(selectBudgetUdefFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(budgetResultsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectBudgetResultsFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paramsPanelLayout = new javax.swing.GroupLayout(paramsPanel);
        paramsPanel.setLayout(paramsPanelLayout);
        paramsPanelLayout.setHorizontalGroup(
            paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paramsPanelLayout.createSequentialGroup()
                .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputFilesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indepPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(budgetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        paramsPanelLayout.setVerticalGroup(
            paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paramsPanelLayout.createSequentialGroup()
                .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indepPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(budgetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputFilesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        consolePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Console"));

        consoleScroller.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        consoleTextArea.setColumns(20);
        consoleTextArea.setRows(5);
        consoleTextArea.setAutoscrolls(true);
        consoleScroller.setViewportView(consoleTextArea);

        javax.swing.GroupLayout consolePanelLayout = new javax.swing.GroupLayout(consolePanel);
        consolePanel.setLayout(consolePanelLayout);
        consolePanelLayout.setHorizontalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consoleScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                .addContainerGap())
        );
        consolePanelLayout.setVerticalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addComponent(consoleScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        oneraLogoPanel.setBackground(new java.awt.Color(255, 255, 255));
        oneraLogoPanel.setBorder(null);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-onera-ident-bd.jpg"))); // NOI18N

        javax.swing.GroupLayout oneraLogoPanelLayout = new javax.swing.GroupLayout(oneraLogoPanel);
        oneraLogoPanel.setLayout(oneraLogoPanelLayout);
        oneraLogoPanelLayout.setHorizontalGroup(
            oneraLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        oneraLogoPanelLayout.setVerticalGroup(
            oneraLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oneraLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paramsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(oneraLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enableIndepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableIndepActionPerformed
    }//GEN-LAST:event_enableIndepActionPerformed

    private void budgetResultsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetResultsFileActionPerformed
    }//GEN-LAST:event_budgetResultsFileActionPerformed

    private void dalRuleMixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dalRuleMixedActionPerformed
    }//GEN-LAST:event_dalRuleMixedActionPerformed

    private void indepUdefFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indepUdefFileActionPerformed
    }//GEN-LAST:event_indepUdefFileActionPerformed

    private void budgetUdefFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetUdefFileActionPerformed
    }//GEN-LAST:event_budgetUdefFileActionPerformed

    private void nofResourcesStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nofResourcesStopActionPerformed
    }//GEN-LAST:event_nofResourcesStopActionPerformed

    private void nofResourcesStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nofResourcesStartActionPerformed
    }//GEN-LAST:event_nofResourcesStartActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DalculatorGui().setVisible(true);
            }
        }
       );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addSeqFile;
    public javax.swing.JCheckBox budgetImportIndep;
    private javax.swing.JPanel budgetPanel;
    public javax.swing.JTextField budgetResultsFile;
    public javax.swing.JTextField budgetUdefFile;
    public javax.swing.JButton cancelAnalysis;
    private javax.swing.JPanel consolePanel;
    private javax.swing.JScrollPane consoleScroller;
    public javax.swing.JTextArea consoleTextArea;
    public javax.swing.JCheckBox dalImportIndep;
    public javax.swing.JPanel dalPanel;
    public javax.swing.JTextField dalResultsFile;
    public javax.swing.JRadioButton dalRule1;
    public javax.swing.JRadioButton dalRule2;
    public javax.swing.ButtonGroup dalRuleGroup;
    public javax.swing.JRadioButton dalRuleMixed;
    public javax.swing.JRadioButton dalSAT4J;
    public javax.swing.ButtonGroup dalSolverGroup;
    public javax.swing.JTextField dalUdefFile;
    public javax.swing.JRadioButton dalWBO;
    public javax.swing.JCheckBox enableBudget;
    public javax.swing.JCheckBox enableDal;
    public javax.swing.JCheckBox enableGlobalLambdaMin;
    public javax.swing.JCheckBox enableIndep;
    public javax.swing.JCheckBox enableMinActive;
    public javax.swing.JCheckBox enableMinCheckItv;
    public javax.swing.JCheckBox enableMinLatent;
    public javax.swing.JCheckBox enableSumActive;
    public javax.swing.JCheckBox enableSumLatent;
    public javax.swing.JPanel indepPanel;
    public javax.swing.JTextField indepResultsFile;
    public javax.swing.JRadioButton indepSAT4J;
    public javax.swing.JCheckBox indepSaveAlloc;
    public javax.swing.ButtonGroup indepSolverGroup;
    public javax.swing.JTextField indepUdefFile;
    public javax.swing.JRadioButton indepWBO;
    private javax.swing.JPanel inputFilesPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logo;
    public javax.swing.JTextField nofResourcesStart;
    public javax.swing.JTextField nofResourcesStop;
    private javax.swing.JPanel oneraLogoPanel;
    private javax.swing.JPanel paramsPanel;
    public javax.swing.JButton removeSeqFile;
    public javax.swing.JButton runAnalysis;
    public javax.swing.JButton selectBudgetResultsFile;
    public javax.swing.JButton selectBudgetUdefFile;
    public javax.swing.JButton selectDalResultsFile;
    public javax.swing.JButton selectDalUdefFile;
    public javax.swing.JButton selectIndepResultsFile;
    public javax.swing.JButton selectIndepUdefFile;
    public javax.swing.JTable seqTable;
    public javax.swing.JScrollPane seqTableScrollPane;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

}
